### ISSUE TITLE
broken link styling: hover on links no longer has a accent underline

### ISSUE THREAD

**Issue by kirontoo** [kirontoo/astro-theme-cody#10]
In `styles/global.css`, it still references hsl colors

```css
 .cody-link {
    @apply bg-[size:100%_6px] bg-bottom bg-repeat-x w-fit;
    background-image: linear-gradient(
      transparent,
      transparent 5px,
      hsl(var(--theme-text)) 5px,
      hsl(var(--theme-text))
    );
  }

  .cody-link:hover {
    background-image: linear-gradient(
      transparent,
      transparent 4px,
      hsl(var(--theme-accent)) 4px,
      hsl(var(--theme-accent))
    );
  }
```
