### ISSUE TITLE
сode font-size in Projects

### ISSUE THREAD

**Issue by DigneZzZ** [kirontoo/astro-theme-cody#36]
Hi Amy,

I'm facing another issue that I can't seem to solve. I can't increase the font size in the code block on the project pages. I was able to do it for the blog and the homepage, but it doesn't work for the project pages. Could you please help me with this?

https://neonode.cc/blog/backup_article/

https://neonode.cc/projects/bench/

**Comment by kirontoo** [comment]
Here's a workaround for the text size issue. You'll need to add the `!important` for it to apply. Alternatively, you could use tailwind to keep the font sizes consistent. If using tailwind, remember to prefix with a `!` -> `!text-lg`.

Add this CSS selector to `.prose-sm :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *))` in `styles/global.css`.

It'll look like this:
```css
  .prose-cody :where(code):not(:where([class~=not-prose], [class~=not-prose] *)),
  .prose-sm :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
     /* if using tailwindcss, add the font-size here */
    @apply bg-accent !text-surface px-1 py-0 !text-lg;

    /* OR
    font-size: 20px !important;
    */
  }

```
